### PR TITLE
Fixing default storage driver

### PR DESCRIPTION
**Pull request by llbbl**
Resolves 
https://github.com/mongrelion/ansible-role-docker/issues/58

### CODE REVIEW

**Review by paulfantom — APPROVED** [review]
lgtm

**Comment by llbbl** [comment]
Not sure why travis failing. Is that something I did ?

**Comment by paulfantom** [comment]
It cannot install `docker-ce` package in version 18.09.1 on Debian Jessie and Ubuntu Xenial. Maybe try with `18.09`?

**Comment by llbbl** [comment]
ok

**Comment by llbbl** [comment]
Trying 18.06.1 now

**Comment by llbbl** [comment]
Worked that time

**Comment by llbbl** [comment]
@paulfantom you ok?

**Comment by paulfantom** [comment]
Wow, that's a blast from a past :D Sorry for a LOOOOOONG delay.

**Comment by llbbl** [comment]
no worries. I get it! thanks for getting this merged.

**Pull request merged**
