### PR TITLE
Only run install script when docker is not installed

### PR DESCRIPTION
**Pull request by mhutter**
This is a suggestion how #16 could be fixed.

### CODE REVIEW

**Comment by marcusianlevine** [comment]
@mongrelion what do you think? LGTM and the changes should not be breaking for any existing use-cases

**Comment by mongrelion** [comment]
Sorry about the delay. I'm currently out of town doing customer job and it's super busy.

Looks good to me as well so :shipit:

**Comment by mongrelion** [comment]
@mhutter this is looking good. Is there anything else holding you back from merging this?

**Comment by mhutter** [comment]
@mongrelion Nope, this can be merged. I already battle-tested it :)

**Pull request merged**
