### PR TITLE
Remove installation script

### LINKED ISSUE #31: Move away from installation script
Using external installation script is convenient but provides zero control over it. Also I don't think it is right way to use ansible.

Script could be rewritten to ansible tasks to provide more control over role as well as clearer output what this role does at the moment.
Here is one role from which tasks could be copy-pasted: https://github.com/SoInteractive/ansible-docker for better installation method.

### PR DESCRIPTION
**Pull request by paulfantom**
Replacing installation script with ansible tasks along with some more cleanup.

Installation method based on previous script and official docs (https://docs.docker.com/install)

Added:
- easier upgrade method (just specify `latest` as `docker_version`)
- testing on `latest` version
- `tasks/configure.yml` file for cleaner look

Removed:
- installation script and everything connected with it
- unused files
- some simple templates
- `docker_upgrade` and `upgrade_docker` variables. Backwards compatibility is maintained by setting `docker_version: latest` when any one of those two vars is detected (not checking value)

Resolves #31

### CODE REVIEW

**Comment by paulfantom** [comment]
After finishing it, I can start work towards #33.

**Comment by paulfantom** [comment]
@mongrelion I think this is ready.

**Comment by paulfantom** [comment]
After merging this I think I could provide a publicly accessible "live" demo usage of this role, by using it [here](https://github.com/cloudalchemy/demo-site/blob/master/extras.yml#L11) instead of current one.

This site is deployed daily and have nice [interface for analysis](https://demo.cloudalchemy.org/ara).

**Comment by mongrelion** [comment]
It's a big change but it's looking good. One thing I noticed, though, is that we don't make sure after installation that Docker is properly running. I'm creating a separate issue for that.

As per the demo, it sounds good to me. Create a separate issue for that and make sure to add a link to the demo on the README :)

**Comment by paulfantom** [comment]
Do we really need to check if it is running? There is this handler: https://github.com/mongrelion/ansible-role-docker/blob/master/handlers/main.yml#L2 also we are having unit tests for this here: https://github.com/mongrelion/ansible-role-docker/blob/master/tests/test_default.py#L37

I think that enabling this: https://github.com/mongrelion/ansible-role-docker/blob/master/tests/test_default.py#L33 would solve most cases

**Pull request merged**
