### PR TITLE
Allow install docker also on RHEL OS

### PR DESCRIPTION
**Pull request by petr-balogh**
This alow install docker-ce also on RHEL OS.
Tested on RHEL 7.5

### CODE REVIEW

**Comment by petr-balogh** [comment]
Hi and thx, are you going to make new release to have this change available in galaxy?

**Comment by paulfantom** [comment]
Not today, but soon.

**Comment by petr-balogh** [comment]
Thx

**Comment by mongrelion** [comment]
Thanks for the PR, @petr-balogh and to @paulfantom for reviewing.
A couple of things that I see missing here that I would have liked to see before merging a pull request like this (but bear with me if I'm missing something, please):

1. I don't see the tests for this but maybe since we already support CentOS, it's already covered for RedHat as well?
2. I also don't see an update on the `meta` to let everyone know that we now support RedHat. Is that also covered by EL/7?

Thanks for the effort, everyone.

**Comment by paulfantom** [comment]
1) CentOS tests cover also RHEL.
2) There is no specific `meta` for RHEL it is covered by EL/7

**Comment by mongrelion** [comment]
Thanks for clarifying.

**Comment by paulfantom** [comment]
No problem :smile:

Sorry for the confusion

**Comment by paulfantom** [comment]
Fun fact, docker basically doesn't have any official builds of docker-ce for RHEL (https://docs.docker.com/install/#server) and they want everybody to use docker-ee on that OS ([installation insctruction for RHEL](https://docs.docker.com/install/linux/docker-ee/rhel/))

Also https://blog.docker.com/2017/03/docker-enterprise-edition

**Pull request merged**
