### PR TITLE
integration tests

### LINKED ISSUE #13: Integration tests
Our current test suite has several issues:

1. It's not automated. If we are to make sure that a developer's change hasn't broken anything, someone has to pull their changes, run the test suite locally and make sure that everything is working accordingly, which bring us to the second point

2. There are no tests whatsoever. The only thing that we are doing is applying the `ansible-role-docker` role with Ansible to the VMs that we create and assume that if no task failed during the run of the playbook, then everything is "fine". We should have a proper test suite that automates all of this, and that has a decent criteria to ensure that the role has been applied successfully and that the installed software (Docker) is behaving as expected (config files in place with proper config params, daemon running & logging, etc.)

Possible options for aiding to this issue are:
* http://serverspec.org/
* https://www.inspec.io/
* https://testinfra.readthedocs.io/en/latest/

If someone has the knowledge or time to dive into testing these tools out (or if they have a better suggestion in mind) and write down below a list of pros/cons for each, that would be great. Otherwise I'll find the time later in August to try them all out with very simple use cases and pick the one that I like the most :P

### PR DESCRIPTION
**Pull request by paulfantom**
Resolves #13 

I've started work towards providing integration tests, currently it works on:
- debian stretch
- ubuntu xenial

And doesn't work on:
- centos 7
- fedora 27
- debian jessie

Problems aren't directly related to integration test suite, but to solutions used in this role (like running installation script instead of porting script to ansible tasks).

I'm currently commenting out not working environments.

### CODE REVIEW

**Comment by paulfantom** [comment]
@mongrelion please check travis output.

I can start work towards integrating some solutions from https://github.com/SoInteractive/ansible-docker to make ansible-lint happy and remove installation script.

**Comment by mongrelion** [comment]
I'm happy to ditch the installation script and replace that with ansible tasks in exchange for a solid test suite.

Keep up the good work!

**Comment by paulfantom** [comment]
Some questions:
1) Can I replace `service` module with newer `systemd` module?
2) This (https://github.com/mongrelion/ansible-role-docker/blob/master/tasks/main.yml#L76) is not used anywhere, remove?
3) This is very static usage of consul: https://github.com/mongrelion/ansible-role-docker/blob/master/tasks/main.yml#L29 probably should be removed or made more dynamic, what do you think?

I think there is a need for a major rework to unify variable naming (variables with role name prefix are easier to read in playbooks) and move from installation script to ansible task. Also I can create some variable mappings for backward compatibility.
But before I start I need to know your point of view on this matter.

**Comment by mongrelion** [comment]
1. If that doesn't break compatibility between the different distros that we support, then go ahead
2. It was used for running tests in Vagrant but since you're moving to Molecule, please remove it
3. This was required back in the days (lol, last year) when support for overlay networks required consul or etcd. This is not required anymore so it can go.

Regarding the unification of variable naming, I agree but I'm afraid it may fall a little out of the scope of this PR so let's keep it nice and tidy and then we can work on the next big thing.
This rework is looking promising.

Thanks again for looking into this!

**Comment by paulfantom** [comment]
Ready to be merged.

Currently it is testing on:
- ubuntu xenial (16.04)
- debian jessie (8)

Distros with SELinux aren't tested since installation script uses `setsebool` command which fails in docker containers due to SELinux beeing in disabled state.

Debian Stretch fails because something fails in the installtion script.

**Comment by paulfantom** [comment]
I am also creating issues so work can be started on other things I discovered during writing this PR

**Comment by mongrelion** [comment]
Awesome work, man. Thanks for this.

**Pull request merged**
