### PR TITLE
readme update

### PR DESCRIPTION
**Pull request by paulfantom**
@mongrelion what do you think about this readme schema?

I've added LICENSE file to master branch, since you mentioned MIT license in readme. Now it displays repo license in the info bar along with "commits, branches, releases, contributors".

### CODE REVIEW

**Comment by mongrelion** [comment]
Not sure if temporary or what but looking at the preview of the README, both the "License" and the "Github Tag" buttons/images won't load.

**Comment by mongrelion** [comment]
Also, could you please add a Contributors section at the bottom of the README with the following list?
- Carlos Leon ([@mongrelion](https://github.com/mongrelion))
- Paweł Krupa ([@paulfantom](https://github.com/paulfantom))
- Marcus Levine ([@marcusianlevine](https://github.com/marcusianlevine))
- Manuel Hutter ([@mhutter](https://github.com/mhutter))
- Dmitri Bichko ([@dbichko](https://github.com/dbichko))
- Zane Westover ([@zanewestover](https://github.com/zanewestover))
- Bruce Becker ([@brucellino](https://github.com/brucellino))
- David Wahlstrom ([@drwahl](https://github.com/drwahl))
- Max Oreshnikov ([@maxim0r](https://github.com/maxim0r))
- Nicholas E. Rabenau ([@nerab](https://github.com/nerab))
- Petr Balogh ([@petr-balogh](https://github.com/petr-balogh))
- ramz ([@ageekymonk](https://github.com/ageekymonk))

Cheers!

**Comment by paulfantom** [comment]
"Github Tag" loads very slowly and I don't know why. It probably uses some slow external service.
As for "License" I don't see any problems in loading.

**Comment by mongrelion** [comment]
Shall we then take the *Github Tag* out of the README? It's nice to have but if it's ain't reliable I don't see value in keeping it.

**Comment by paulfantom** [comment]
It's out

**Comment by mongrelion** [comment]
:shipit: you can go ahead and merge.

**Pull request merged**
