### PR TITLE
Automatically create releases and changelog

### LINKED ISSUE #34: Auto-release?
I can provide a script to be included in travis CI pipeline which can automatically set new tags following [semantic versioning](https://semver.org/).
It runs only on master branch and by default it adds 1 to PATCH part of varsion tag when something new is pushed. It also can add 1 to MAJOR part when it detects special message in the last commit.
This is how it looks: https://github.com/cloudalchemy/ansible-prometheus/blob/master/.travis/generatetag.sh

### PR DESCRIPTION
**Pull request by paulfantom**
Resolves #34 

This needs setting `GH_TOKEN` variable in travis ci pipeline settings. `GH_TOKEN` should store github token with repo.public_repo scope.

### CODE REVIEW

**Comment by mongrelion** [comment]
@paulfantom do you have the necessary rights to generate the `GH_TOKEN`? do you need anything from me?

**Comment by paulfantom** [comment]
It depends on whose account will be commiting changes. For example in @cloudalchemy we decided to create another account (@cloudalchemybot) just for this task. If you want I can configure this account to do the same here otherwise it would be best if `GH_TOKEN` was generated by you.

**Comment by mongrelion** [comment]
For this first iteration let's use the token generated by me. I would like to see how it works in the mid term and if it proves to be nice and easy, then do the bot account.

**Comment by mongrelion** [comment]
@paulfantom it's not clear to me how I can create this token. Is it a webhook token? a service? what is it? ;P

**Comment by paulfantom** [comment]
You need to generate Github token in https://github.com/settings/tokens with scope `repo.public_repo`. Next you need to setup variable `GH_TOKEN` in travis pipeline with the value of an already created token.

Docs:
- [Creating GitHub token](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/)
- [Travis env variables](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings)

**Comment by mongrelion** [comment]
Done.

**Comment by paulfantom** [comment]
Ok, I think this is ready.

@mongrelion please check line https://github.com/mongrelion/ansible-role-docker/pull/43/files#diff-a0b30116c102965add65f930c8b9c5a7R28 to verify if this is your email address.

**Comment by mongrelion** [comment]
lgtm

**Comment by paulfantom** [comment]
Ok, I'm merging it and will try if automatic releases work with `v` prefix. Supposed release should be `v0.1.1`

**Comment by paulfantom** [comment]
Looks like it understands `v` prefix but tags without it. Is this acceptable?

**Comment by mongrelion** [comment]
Sure. I'm ok with dropping the `v` from the tags to make this work. Not a big deal.
Could you fix the `v0.1.0` issue? Probably the best is to delete that tag, create a new one `0.1.0` and update the changelog file.
Also I think it's fine to push just to `master` directly for this fix.

**Comment by paulfantom** [comment]
Done. I have also created a github release for tag 0.1.0.

**Pull request merged**
