### PR TITLE
added a way to add insecure registries

### PR DESCRIPTION
**Pull request by costypetrisor**

### CODE REVIEW

**Comment by mongrelion** [comment]
Hello, @costypetrisor 

Thanks for submitting this PR.
I'm going to put this on hold for the moment since there is another PR (#10) that seems to cover your use case and many others in a more elegant way.

I'll keep you posted

**Comment by mongrelion** [comment]
@costypetrisor the PR #10 has landed. Can you make sure that you pull the latest changes and see if the new exposed docker configuration variable works for the use case that you're trying to cover here?

Cheers!

**Comment by mhutter** [comment]
should work like this:

    docker_config:
      insecure-registry: your.registry

**Comment by costypetrisor** [comment]
Indeed, everything works. Thank you both for the great work! :)
I should of checked #10 existed first ...

**Comment by mongrelion** [comment]
@costypetrisor no worries. To be fair, you both submitted your PRs with only a few hours of difference :o

**Pull request closed without merging**
